scene:
    _target_: torchngp.io.load_scene_from_json
    path: data/trivial/transforms.json
    pose_to_cv: true
volume:
    _target_: torchngp.volumes.Volume
    aabb: ${scene.aabb}
    radiance_field:
        _target_: torchngp.radiance.NeRF
        n_colors: 3
        n_hidden: 64
        n_encodings_log2: 18
        n_levels: 16
        n_color_cond: 16
        min_res: 32
        max_res: 512
        max_res_dense: 256
        is_hdr: false
    spatial_filter:
        _target_: torchngp.filtering.OccupancyGridFilter
        res: 128
        density_initial: 0.04
        density_threshold: 0.01
        stochastic_test: true
        update_decay: 0.7
        update_noise_scale: null
        update_selection_rate: 0.25
train_renderer:
    _target_: torchngp.rendering.RadianceRenderer
    tsampler:
        _target_: torchngp.sampling.StratifiedRayStepSampler
        n_samples: 512
    ray_extension: 10.0
val_renderer:
    _target_: torchngp.rendering.RadianceRenderer
    tsampler:
        _target_: torchngp.sampling.StratifiedRayStepSampler
        n_samples: 512
    ray_extension: 10.0
trainer:
    _target_: torchngp.training.NeRFTrainer
    output_dir: ${hydra:runtime.output_dir}
    train_cam_idx: 0
    train_slice: ":3"
    train_max_time: 600.0
    val_cam_idx: -1
    val_slice: ":3"
    n_rays_batch_log2: 13
    n_rays_minibatch_log2: 13
    n_worker: 4
    use_amp: true
    random_uv: true
    subpixel_uv: true
    preload: false
    optimizer:
        _target_: torchngp.training.OptimizerParams
        lr: 0.01
        betas:
            - 0.9
            - 0.99
        eps: 1.0e-15
        decay_encoder: 0.0
        decay_density: 1.0e-06
        decay_color: 1.0e-06
        sched_factor: 0.75
        sched_patience: 200
        sched_minlr: 0.0001
    dev: null
    callbacks:
        -   _target_: torchngp.training.UpdateSpatialFilterCallback
            n_rays_interval_log2: 15
        -   _target_: torchngp.training.ValidationCallback
            n_rays_interval_log2: 20