log_level: info
dataset: ???
nerf: ???
train:
    n_rays_batch: 16384 # 2**14
    n_rays_minibatch: 16384 # 2**14
    n_worker: 4
    preload: false
    use_amp: true
    random_uv: true
    subpixel_uv: true
    opt:
        lr: 1e-2
        betas: [0.9, 0.99]
        eps: 1e-15
        decay_encoder: 0.0
        decay_density: 1e-6
        decay_color: 1e-6
    sched:
        factor: 0.75
        patience: 20
        min_lr: 1e-4
    val_interval: 1e7
    val_min_loss: 5e-3
occupancy:
    res: 64
    density_initial: 0.02
    update_interval: 8
    stochastic_test: true
step_sampler:
    type: stratified
    n_samples: 512

defaults:
    - dataset: lego
    - nerf: default
    - _self_
