train:
    _target_: torchngp.io.MultiViewScene
    path: data/suzanne/transforms.json
    slice: ":-3"
val:
    _target_: torchngp.io.MultiViewScene
    path: data/lego/transforms_val.json
    slice: "-3:"
