train_renderer:
    _target_: torchngp.modules.RadianceRenderer
    tsampler:
        _target_: torchngp.modules.StratifiedRayStepSampler
        n_samples: 1024
    tfar_scale: 10
val_renderer:
    _target_: torchngp.modules.RadianceRenderer
    tsampler:
        _target_: torchngp.modules.StratifiedRayStepSampler
        n_samples: 2024
    tfar_scale: 10
