train_renderer:
    _target_: torchngp.modules.RadianceRenderer
    tsampler:
        _target_: torchngp.modules.StratifiedRayStepSampler
        n_samples: 1024
    ray_ext_factor: 10.0
val_renderer:
    _target_: torchngp.modules.RadianceRenderer
    tsampler:
        _target_: torchngp.modules.StratifiedRayStepSampler
        n_samples: 1024
    ray_ext_factor: 10.0
