train_renderer:
    _target_: torchngp.modules.RadianceRenderer
    tsampler:
        _target_: torchngp.modules.StratifiedRayStepSampler
        n_samples: 512
val_renderer:
    _target_: torchngp.modules.RadianceRenderer
    tsampler:
        _target_: torchngp.modules.StratifiedRayStepSampler
        n_samples: 512
