_target_: torchngp.modules.Volume
aabb: "${data.aabb}"
radiance_field:
    _target_: torchngp.modules.NeRF
    n_colors: 3
    n_hidden: 64
    n_encodings_log2: 19
    n_levels: 16
    n_color_cond: 15
    min_res: 16
    max_res: 2048
    max_res_dense: 256
    is_hdr: false
spatial_filter:
    _target_: torchngp.modules.OccupancyGridFilter
    res: 128
    density_initial: 0.04
    density_threshold: 0.01
    stochastic_test: true
    update_decay: 0.8
    update_noise_scale: null
    update_selection_rate: 0.5
