_target_: torchngp.volumes.Volume
aabb: "${data.aabb}"
radiance_field:
    _target_: torchngp.radiance.NeRF
    n_colors: 3
    n_hidden: 64
    n_encodings_log2: 18
    n_levels: 16
    n_color_cond: 16
    min_res: 16
    max_res: 2048
    max_res_dense: 256
    is_hdr: false
spatial_filter:
    _target_: torchngp.filtering.OccupancyGridFilter
    res: 128
    density_initial: 0.04
    density_threshold: 0.01
    stochastic_test: true
    update_decay: 0.7
    update_noise_scale: null
    update_selection_rate: 0.25
